export const MODELS_LIST = [
	'tiny',
	'tiny.en',
	'tiny-q5_1',
	'tiny.en-q5_1',
	'base',
	'base.en',
	'base-q5_1',
	'base.en-q5_1',
	'small',
	'small.en',
	'small.en-tdrz',
	'small-q5_1',
	'small.en-q5_1',
	'medium',
	'medium.en',
	'medium-q5_0',
	'medium.en-q5_0',
	'large-v1',
	'large-v2',
	'large-v2-q5_0',
	'large-v3',
	'large-v3-q5_0',
]

export const MODELS = [
	'ggml-tiny.bin',
	'ggml-tiny.en.bin',
	'ggml-tiny-q5_1.bin',
	'ggml-tiny.en-q5_1.bin',
	'ggml-base.bin',
	'ggml-base.en.bin',
	'ggml-base-q5_1.bin',
	'ggml-base.en-q5_1.bin',
	'ggml-small.bin',
	'ggml-small.en.bin',
	'ggml-small.en-tdrz.bin',
	'ggml-small-q5_1.bin',
	'ggml-small.en-q5_1.bin',
	'ggml-medium.bin',
	'ggml-medium.en.bin',
	'ggml-medium-q5_0.bin',
	'ggml-medium.en-q5_0.bin',
	'ggml-large-v1.bin',
	'ggml-large-v2.bin',
	'ggml-large-v2-q5_0.bin',
	'ggml-large-v3.bin',
	'ggml-large-v3-q5_0.bin',
]

export const MODEL_OBJECT = {
	tiny: 'ggml-tiny.bin',
	'tiny.en': 'ggml-tiny.en.bin',
	'tiny-q5_1': 'ggml-tiny-q5_1.bin',
	'tiny.en-q5_1': 'ggml-tiny.en-q5_1.bin',
	base: 'ggml-base.bin',
	'base.en': 'ggml-base.en.bin',
	'base-q5_1': 'ggml-base-q5_1.bin',
	'base.en-q5_1': 'ggml-base.en-q5_1.bin',
	small: 'ggml-small.bin',
	'small.en': 'ggml-small.en.bin',
	'small.en-tdrz': 'ggml-small.en-tdrz.bin',
	'small-q5_1': 'ggml-small-q5_1.bin',
	'small.en-q5_1': 'ggml-small.en-q5_1.bin',
	medium: 'ggml-medium.bin',
	'medium.en': 'ggml-medium.en.bin',
	'medium-q5_0': 'ggml-medium-q5_0.bin',
	'medium.en-q5_0': 'ggml-medium.en-q5_0.bin',
	'large-v1': 'ggml-large-v1.bin',
	'large-v2': 'ggml-large-v2.bin',
	'large-v2-q5_0': 'ggml-large-v2-q5_0.bin',
	'large-v3': 'ggml-large-v3.bin',
	'large-v3-q5_0': 'ggml-large-v3-q5_0.bin',
}

export const DEFAULT_MODEL = 'tiny.en'
